version: "2"
services:
    pystok-fdw:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            API_URL: 'http://api:80'
        depends_on:
            - api
    api:
        build:
            context: api
            dockerfile: Dockerfile
        ports:
            - "80:80"
